# Generated by Django 5.1.5 on 2025-01-31 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ClassApp', '0005_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='eventbanner',
            field=models.ImageField(default='', upload_to='media/EventBanners'),
            preserve_default=False,
        ),
    ]
