# Generated by Django 5.1.5 on 2025-02-01 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ClassApp', '0006_event_eventbanner'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='is_paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='event',
            name='eventbanner',
            field=models.ImageField(upload_to='EventBanners'),
        ),
        migrations.AlterField(
            model_name='event',
            name='form',
            field=models.FileField(blank=True, null=True, upload_to='forms/'),
        ),
    ]
