# Generated by Django 5.1.5 on 2025-02-18 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ClassApp', '0008_grade_alter_profile_grade'),
    ]

    operations = [
        migrations.RenameField(
            model_name='grade',
            old_name='feeamount',
            new_name='AdmissionFee',
        ),
        migrations.AddField(
            model_name='grade',
            name='Totalfeeamount',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
