# Generated by Django 5.1.5 on 2025-02-18 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ClassApp', '0009_rename_feeamount_grade_admissionfee_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grade',
            name='classname',
            field=models.CharField(choices=[('1', 'Grade 1'), ('2', 'Grade 2'), ('3', 'Grade 3'), ('4', 'Grade 4'), ('5', 'Grade 5'), ('6', 'Grade 6'), ('7', 'Grade 7'), ('8', 'Grade 8'), ('9', 'Grade 9'), ('10', 'Grade 10')], unique=True),
        ),
    ]
