# Generated by Django 5.1.5 on 2025-02-18 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ClassApp', '0012_alter_profile_options_alter_profile_managers_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='grade',
            name='monthlyfee',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
