# Generated by Django 5.1.5 on 2025-02-18 16:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ClassApp', '0013_grade_monthlyfee'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grade',
            name='monthlyfee',
        ),
    ]
