# Generated by Django 5.1.5 on 2025-02-18 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ClassApp', '0014_remove_grade_monthlyfee'),
    ]

    operations = [
        migrations.AddField(
            model_name='grade',
            name='paidFees',
            field=models.IntegerField(default=0),
        ),
    ]
