# Generated by Django 5.1.5 on 2025-02-21 06:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ClassApp', '0016_notification'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grade',
            name='AdmissionFee',
        ),
        migrations.RemoveField(
            model_name='grade',
            name='Totalfeeamount',
        ),
        migrations.RemoveField(
            model_name='grade',
            name='paidFees',
        ),
        migrations.CreateModel(
            name='PaymentStructure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Totalfeeamount', models.IntegerField()),
                ('paidFees', models.IntegerField(default=0)),
                ('AdmissionFee', models.IntegerField()),
                ('grade', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payment_structure', to='ClassApp.grade')),
            ],
        ),
    ]
