# Generated by Django 5.1.5 on 2025-02-21 07:12

import ClassApp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ClassApp', '0017_remove_grade_admissionfee_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='grade',
            name='academic_year',
            field=models.CharField(default=ClassApp.models.get_academic_year, max_length=9),
        ),
        migrations.AlterField(
            model_name='grade',
            name='classname',
            field=models.CharField(choices=[('1', 'Grade 1'), ('2', 'Grade 2'), ('3', 'Grade 3'), ('4', 'Grade 4'), ('5', 'Grade 5'), ('6', 'Grade 6'), ('7', 'Grade 7'), ('8', 'Grade 8'), ('9', 'Grade 9'), ('10', 'Grade 10')], max_length=2),
        ),
        migrations.AlterUniqueTogether(
            name='grade',
            unique_together={('classname', 'academic_year')},
        ),
        migrations.AlterModelTable(
            name='grade',
            table='grade_table',
        ),
    ]
