# Generated by Django 5.1.5 on 2025-02-21 10:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ClassApp', '0018_grade_academic_year_alter_grade_classname_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentstructure',
            name='user',
            field=models.ForeignKey(default=39, on_delete=django.db.models.deletion.CASCADE, to='ClassApp.profile'),
            preserve_default=False,
        ),
    ]
