# Generated by Django 5.1.5 on 2025-02-21 10:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ClassApp', '0020_remove_paymentstructure_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='payment_structure',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='profile', to='ClassApp.paymentstructure'),
        ),
    ]
