# Generated by Django 5.1.5 on 2025-03-08 13:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ClassApp', '0021_profile_payment_structure'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paymentstructure',
            name='paidFees',
        ),
        migrations.AlterField(
            model_name='profile',
            name='grade',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ClassApp.grade'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='payment_structure',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='profiles', to='ClassApp.paymentstructure'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('Teacher', 'Teacher'), ('Student', 'Student')], max_length=10, verbose_name='Role'),
        ),
        migrations.CreateModel(
            name='FeePayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_paid', models.IntegerField()),
                ('payment_date', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fee_payments', to='ClassApp.profile')),
            ],
        ),
    ]
