# Generated by Django 5.1.5 on 2025-03-16 01:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ClassApp', '0022_remove_paymentstructure_paidfees_alter_profile_grade_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notification',
            old_name='user',
            new_name='user_instance',
        ),
    ]
