# Generated by Django 5.1.5 on 2025-03-22 13:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ClassApp', '0023_rename_user_notification_user_instance'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='profile_picture',
            field=models.ImageField(null=True, upload_to='profilePictures', verbose_name='Enter Your Profile Picture here'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='grade',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ClassApp.grade'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='payment_structure',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='profiles', to='ClassApp.paymentstructure'),
        ),
    ]
