# Generated by Django 5.1.5 on 2025-03-27 14:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ClassApp', '0024_profile_profile_picture_alter_profile_grade_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Exam_Name', models.CharField(max_length=255)),
                ('Exam_Date', models.DateField(max_length=255)),
                ('Created_by', models.CharField(max_length=255)),
                ('Total_Marks', models.CharField(max_length=255)),
                ('ExamGrade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ClassApp.grade')),
            ],
        ),
        migrations.CreateModel(
            name='questions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Question_Name', models.CharField(max_length=255)),
                ('Question_Marks', models.CharField(max_length=100)),
                ('Exam_Instace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ClassApp.exam')),
            ],
        ),
        migrations.CreateModel(
            name='choice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice_name', models.CharField(max_length=255, verbose_name='Answer')),
                ('question_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ClassApp.questions')),
            ],
        ),
        migrations.CreateModel(
            name='StudentAnswers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('StudentAnswers', models.CharField(max_length=255, null=True, verbose_name='Student_ID')),
                ('question_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ClassApp.questions')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
