# Generated by Django 5.1.5 on 2025-03-28 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ClassApp', '0026_alter_exam_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='questions',
            name='correct_answer',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
