# Generated by Django 5.1.5 on 2025-03-29 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ClassApp', '0028_studentleaderboard'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentleaderboard',
            name='total_marks',
            field=models.IntegerField(max_length=10),
        ),
    ]
