# Generated by Django 5.1.5 on 2025-03-29 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ClassApp', '0029_alter_studentleaderboard_total_marks'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentleaderboard',
            name='Answered',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='studentleaderboard',
            name='Correct',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='studentleaderboard',
            name='Incorrect',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='studentleaderboard',
            name='total_marks',
            field=models.IntegerField(),
        ),
    ]
