# Generated by Django 5.1.5 on 2025-03-29 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ClassApp', '0030_studentleaderboard_answered_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentleaderboard',
            name='Total_Question',
            field=models.IntegerField(null=True),
        ),
    ]
