# Generated by Django 5.1.5 on 2025-04-03 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ClassApp', '0032_attendance'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='Attendance_Status',
            field=models.CharField(null=True, verbose_name='Attendnace Status'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='profilePictures', verbose_name='Enter Your Profile Picture here'),
        ),
    ]
