# Generated by Django 5.1.5 on 2025-04-03 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ClassApp', '0033_attendance_attendance_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='student_id',
            field=models.CharField(blank=True, null=True),
        ),
    ]
