# Generated by Django 5.1.5 on 2025-04-09 13:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ClassApp', '0034_profile_student_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='created_at',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='notification',
            name='tag',
            field=models.CharField(choices=[('Fees', 'Fees'), ('General', 'General'), ('Holiday', 'Holiday'), ('Exam', 'Exam'), ('Profile', 'Profile')], default='General', max_length=255),
        ),
        migrations.AlterField(
            model_name='profile',
            name='profile_picture',
            field=models.ImageField(blank=True, default='profilePictures/DefaultPP.jpg', null=True, upload_to='profilePictures0,', verbose_name='Enter Your Profile Picture here'),
        ),
    ]
