# Generated by Django 5.1.5 on 2025-04-10 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ClassApp', '0035_notification_created_at_notification_tag_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Holiday',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Holiday_Name', models.CharField(max_length=300)),
                ('Holiday_Date', models.DateField()),
                ('End_DateField', models.DateField()),
                ('School_ResumeDate', models.DateField()),
                ('Duration', models.CharField(max_length=255)),
                ('Type', models.CharField(verbose_name='Type of Holiday')),
            ],
        ),
    ]
