# Generated by Django 5.1.5 on 2025-04-10 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ClassApp', '0036_holiday'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feepayment',
            name='payment_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='holiday',
            name='Duration',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
