# Generated by Django 5.1.5 on 2025-04-14 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ClassApp', '0038_alter_profile_grade_alter_profile_payment_structure_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='form',
            field=models.URLField(blank=True, null=True),
        ),
    ]
