# Generated by Django 5.1.5 on 2025-04-14 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ClassApp', '0039_alter_event_form'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='tag',
            field=models.CharField(blank=True, choices=[('Music', 'Music'), ('Arts', 'Arts'), ('Sports', 'Sports'), ('Education', 'Education'), ('Drama', 'Drama'), ('Literature', 'Literature'), ('Computer Science', 'Computer Science'), ('Science', 'Science'), ('Mathematics', 'Mathematics'), ('Languages', 'Languages'), ('School Events', 'School Events'), ('Club Activities', 'Club Activities'), ('Robotics', 'Robotics'), ('Design', 'Design'), ('Leadership', 'Leadership')], null=True),
        ),
    ]
