# Generated by Django 5.1.5 on 2025-04-14 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ClassApp', '0040_event_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='Notificationtitle',
            field=models.CharField(blank=True, null=True, verbose_name='title name '),
        ),
    ]
