# Generated by Django 5.1.5 on 2025-04-14 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ClassApp', '0041_notification_notificationtitle'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='holiday',
            name='End_DateField',
        ),
        migrations.RemoveField(
            model_name='holiday',
            name='Type',
        ),
        migrations.AlterField(
            model_name='notification',
            name='tag',
            field=models.CharField(choices=[('Fees', 'Fees'), ('General', 'General'), ('Government', 'Government'), ('Exam', 'Exam'), ('Profile', 'Profile'), ('Holiday', 'Holiday')], default='General', max_length=255),
        ),
    ]
