# Generated by Django 5.1.5 on 2025-04-19 17:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ClassApp', '0044_profile_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='feepayment',
            name='grade',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ClassApp.grade'),
        ),
    ]
