# Generated by Django 5.2 on 2025-04-23 12:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ClassApp', '0045_feepayment_grade'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StudentAnswers',
        ),
    ]
