# Generated by Django 5.2 on 2025-04-23 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ClassApp', '0046_delete_studentanswers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='form',
            field=models.URLField(default="    eventbanner = models.ImageField(upload_to='EventBanners',null=False)"),
            preserve_default=False,
        ),
    ]
